---
step_ca_url: https://dl.step.sm/gh-release/certificates/docs-ca-install/v0.22.0/step-ca_0.22.0_amd64.deb
step_url: https://dl.step.sm/gh-release/cli/docs-ca-install/v0.22.0/step-cli_0.22.0_amd64.deb

step_ca_image: ghcr.io/noosxe/homelab/step-ca-debian:latest

podman_bin: /usr/bin/podman

password_file: password.txt
config_file: config/ca.json

ca_dir: /etc/step-ca
ca_usb_dir: "{{ ca_dir }}/usb"
ca_tmp_dir: "{{ ca_dir }}/tmp"
ca_json: "{{ ca_dir }}/{{ config_file }}"
ca_user: step
ca_uid: 1500
ca_name: tinyca
ca_dns: tinyca.local
ca_provisioner: kirlevon@gmail.com
