---
- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip

- name: Install docker sdk
  become: true
  ansible.builtin.pip:
    name: docker==6.0.0

- name: Install usb serial drivers
  become: true
  ansible.builtin.apt:
    name: linux-image-extra-virtual
