---
- name: Grow partition
  become: true
  ansible.builtin.command: growpart /dev/sda 1
  ignore_errors: true

- name: resize2fs
  become: true
  ansible.builtin.command: resize2fs /dev/sda1
  ignore_errors: true

- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: systemd
  when: hostname is defined

- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ name }}"
    use: systemd
  when: hostname is not defined

- name: Place the hosts file
  become: true
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts

- name: Set timezone to America/Los_Angeles
  become: true
  community.general.timezone:
    name: America/Los_Angeles

- name: Update apt-get repo and cache
  become: true
  ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  become: true
  ansible.builtin.apt: upgrade=dist force_apt_get=yes

- name: Check if a reboot is needed
  register: reboot_required_file
  ansible.builtin.stat: path=/var/run/reboot-required get_md5=no

- name: Reboot the Debian or Ubuntu server
  become: true
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists

- name: Install qemu-guest-agent
  become: true
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present

- name: Enable and start qemu-guest-agent
  become: true
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true

- name: Install nfs-common
  become: true
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Allow OpenSSH
  become: true
  community.general.ufw:
    rule: allow
    name: OpenSSH
    src: 192.168.10.0/24

- name: Deny everything and enable UFW
  become: true
  community.general.ufw:
    state: enabled
    policy: deny
