---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: systemd
  when: hostname is defined

- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ name }}"
    use: systemd
  when: hostname is not defined

- name: Place the hosts file
  become: true
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts

- name: Set timezone to America/Los_Angeles
  become: true
  community.general.timezone:
    name: America/Los_Angeles

- name: Install qemu-guest-agent
  become: true
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present

- name: Enable and start qemu-guest-agent
  become: true
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true

- name: Install nfs-common
  become: true
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Allow OpenSSH
  become: true
  community.general.ufw:
    rule: allow
    name: OpenSSH
    src: 192.168.10.0/24

- name: Deny everything and enable UFW
  become: true
  community.general.ufw:
    state: enabled
    policy: deny
