---
- name: Start step CA
  become: true
  systemd:
    daemon_reload: yes
    name: step-ca
    enabled: yes
    state: restarted

- name: Reload udevadm
  become: true
  shell: udevadm control --reload-rules
