---
- name: Start step CA
  become: true
  systemd:
    name: step-ca
    daemon-reload: yes
    enabled: yes
    state: restarted

- name: Reload udevadm
  become: true
  shell: udevadm control --reload-rules
