---
- name: Start step CA
  become: true
  ansible.builtin.systemd:
    name: step-ca
    daemon-reload: true
    enabled: true
    state: restarted

- name: Reload udevadm
  become: true
  ansible.builtin.command: udevadm control --reload-rules
