---
- name: Ensure group exists
  become: true
  ansible.builtin.group:
    name: "{{ group.name }}"
    gid: "{{ group.gid }}"
    state: present
  when: group is defined

- name: Stat the mount dir
  become: true
  ansible.builtin.stat:
    path: "{{ dest }}"
  register: dest_dir

- name: Create the mount dir
  become: true
  ansible.builtin.file:
    path: "{{ dest }}"
    state: directory
    mode: "0755"
  when: not dest_dir.stat.exists

- name: Mount the nfs share
  become: true
  ansible.posix.mount:
    src: "{{ src }}"
    path: "{{ dest }}"
    opts: vers=4,rw,sync,hard,intr,tcp,nofail,noatime,nolock
    state: mounted
    fstype: nfs
