---
- name: Restart smbd service
  become: true
  ansible.builtin.service:
    name: smbd
    state: restarted
    enabled: true

- name: Restart avahi-daemon service
  become: true
  ansible.builtin.service:
    name: avahi-daemon
    state: restarted
    enabled: true
