---
- name: Restart smbd service
  become: true
  service:
    name: smbd
    state: restarted
    enabled: true

- name: Restart avahi-daemon service
  become: true
  service:
    name: avahi-daemon
    state: restarted
    enabled: true

- name: reset ssh connection
  meta: reset_connection
