---
- name: Allow ldap
  become: true
  community.general.ufw:
    rule: allow
    name: OpenLDAP LDAPS
    src: 192.168.10.0/24

- name: Allow Apache Secure
  become: true
  community.general.ufw:
    rule: allow
    name: Apache Secure
    src: 192.168.10.0/24
