---
- name: Allow ldaps
  become: true
  community.general.ufw:
    rule: allow
    port: "636"
    src: 192.168.10.0/24

- name: Allow HTTP
  become: true
  community.general.ufw:
    rule: allow
    port: "80"
    src: 192.168.10.0/24

- name: Allow HTTPS
  become: true
  community.general.ufw:
    rule: allow
    port: "443"
    src: 192.168.10.0/24
