---
- name: Include secrets
  include_vars: ../../../secrets.yaml

- name: Install packages
  import_tasks: pkgs.yaml

- name: Setup firewall
  import_tasks: firewall.yaml

- name: Setup certbot
  import_tasks: certbot.yaml

- name: Setup openldap
  import_tasks: openldap.yaml

- name: Setup phpldapadmin
  import_tasks: phpldapadmin.yaml
