---
- name: Include secrets
  ansible.builtin.include_vars: ../../../secrets.yaml

- name: Install packages
  ansible.builtin.import_tasks: pkgs.yaml

- name: Setup firewall
  ansible.builtin.import_tasks: firewall.yaml

- name: Setup certbot
  ansible.builtin.import_tasks: certbot.yaml

- name: Setup openldap
  ansible.builtin.import_tasks: openldap.yaml

- name: Setup phpldapadmin
  ansible.builtin.import_tasks: phpldapadmin.yaml
