---
- name: Configure slapd install settings
  become: true
  ansible.builtin.debconf:
    name: slapd
    question: "{{ item['question'] }}"
    value: "{{ item['value'] }}"
    vtype: "{{ item['vtype'] }}"
  loop:
    - question: slapd/internal/generated_adminpw
      value: "{{ openldap_admin_password }}"
      vtype: password
    - question: slapd/password2
      value: "{{ openldap_admin_password }}"
      vtype: password
    - question: slapd/internal/adminpw
      value: "{{ openldap_admin_password }}"
      vtype: password
    - question: slapd/password1
      value: "{{ openldap_admin_password }}"
      vtype: password
    - question: slapd/domain
      value: "{{ openldap_domain_name }}"
      vtype: string
    - question: shared/organization
      value: "{{ openldap_org }}"
      vtype: string
    - question: slapd/backend
      value: "{{ openldap_db_engine }}"
      vtype: string

- name: Install packages
  become: true
  ansible.builtin.apt:
    name:
      - slapd
      - ldap-utils

- name: Add openldap user to ssl-cert group
  become: true
  user:
    name: openldap
    groups: ssl-cert
    append: yes

- name: Allow ldaps:///
  become: true
  lineinfile:
    path: /etc/default/slapd
    regexp: "SLAPD_SERVICES="
    line: SLAPD_SERVICES="ldap:/// ldapi:/// ldaps:///"

- name: Restart slapd
  become: true
  systemd:
    name: slapd
    state: restarted

- name: Place ssl config ldif
  become: true
  template:
    src: ssl.ldif.j2
    dest: /root/ssl.ldif
    mode: "0644"

- name: Run slapmodify to configure ssl support
  become: true
  command: ldapmodify -H ldapi:// -Y EXTERNAL -f /root/ssl.ldif
