---
- name: Install ubuntu acl package
  become: true
  apt:
    name: acl

- name: Install ssl-cert
  become: true
  apt:
    name: ssl-cert

- name: Install step-cli
  become: true
  apt:
    deb: "{{ step_url }}"

- name: Install phpldapadmin
  become: true
  apt:
    name: phpldapadmin
