---
- name: Install packages
  ansible.builtin.import_tasks: pkgs.yaml

- name: Ensure the group exists
  become: true
  ansible.builtin.group:
    name: "{{ linux_group.name }}"
    state: present
    gid: "{{ linux_group.gid }}"

- name: Ensure the user exists
  become: true
  ansible.builtin.user:
    name: "{{ linux_user.name }}"
    uid: "{{ linux_user.uid }}"
    group: "{{ linux_group.name }}"

- name: Ensure the uptime-kuma dir exists
  become: true
  become_user: "{{ linux_user.name }}"
  ansible.builtin.file:
    path: "{{ data_dir }}"
    state: directory
    mode: "0770"

- name: Create the container
  become: true
  community.docker.docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma:1.18.5-debian
    restart_policy: always
    volumes:
      - "{{ data_dir }}:/app/data"
    env:
      PUID: "{{ linux_user.uid }}"
      PGID: "{{ linux_user.gid }}"
