---
- name: Include secrets
  include_vars: ../../../secrets.yaml

- name: Install packages
  import_tasks: pkgs.yaml

- name: Install root certificate
  become: true
  command: step ca bootstrap --install --force --ca-url={{ tiny_ca_url }} --fingerprint={{ root_fingerprint }}
