---
- name: Include secrets
  ansible.builtin.include_vars: ../../../secrets.yaml

- name: Install packages
  ansible.builtin.import_tasks: pkgs.yaml

- name: Install root certificate
  become: true
  ansible.builtin.command: step ca bootstrap --install --force --ca-url={{ tiny_ca_url }} --fingerprint={{ root_fingerprint }}
