- name: Dockerhost Proxmox
  hosts: proxmox
  roles:
    - role: proxmox_base
      vms: "{{ groups['dockerhost'] | map('extract',hostvars) | list }}"
      when: dockerhost_full is defined
    - role: nfs_server
      vars:
        path: store/dockerhost
        sharenfs: "rw=@192.168.10.105,anongid=7000,anonuid=7000,all_squash"
        group:
          name: dockerhost
          gid: 7000
        user:
          name: dockerhost
          uid: 7000
      when: dockerhost_full is defined
    - role: nfs_server
      vars:
        path: store/media
        sharenfs: "rw=@192.168.10.0/24,anongid=6000,anonuid=6000,all_squash"
        group:
          name: shares
          gid: 6000
        user:
          name: shares
          uid: 6000
      when: dockerhost_full is defined

- name: Dockerhost
  hosts: dockerhost
  roles:
    - basic_vm
    - tinyca_client
    - role: nfs_client
      vars:
        group:
          name: dockerhost
          gid: 7000
        src: 192.168.10.58:/mnt/store/dockerhost
        dest: /mnt/dockerhost
    - role: nfs_client
      vars:
        group:
          name: shares
          gid: 6000
        src: 192.168.10.58:/mnt/store/media
        dest: /mnt/media
    - docker
    - role: caddy
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: caddy
          uid: 10001
          gid: 7000
        data_dir: /mnt/dockerhost/caddy
    - role: portainer
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: portainer
          uid: 10002
          gid: 7000
        data_dir: /mnt/dockerhost/portainer
    - role: vault
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: vault
          uid: 10003
          gid: 7000
        data_dir: /mnt/dockerhost/vault
    - role: jellyfin
      vars:
        linux_group:
          name: shares
          gid: 6000
        linux_user:
          name: jellyfin
          uid: 10004
          gid: 6000
        data_dir: /mnt/dockerhost/jellyfin
        media_dir: /mnt/media
    - role: uptime_kuma
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: uptime_kuma
          uid: 7000
          gid: 7000
        data_dir: /mnt/dockerhost/uptime_kuma
    - role: code-server
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: code_server
          uid: 10005
          gid: 7000
        data_dir: /mnt/dockerhost/code-server
    - role: docker_network
      vars:
        name: dockerhost
        connected:
          - caddy
          - portainer
          - vault
          - jellyfin
          - uptime-kuma
          - code-server
