- name: Dockerhost Proxmox
  hosts: proxmox
  roles:
    - role: proxmox_base
      vms: "{{ groups['dockerhost'] | map('extract',hostvars) | list }}"
      when: dockerhost_full is defined
    - role: nfs_server
      vars:
        path: store/dockerhost/portainer
        sharenfs: "rw=@192.168.10.105"
        group:
          name: dockerhost
          gid: 7000
      when: dockerhost_full is defined

- name: Dockerhost
  hosts: dockerhost
  roles:
    - basic_vm
    - tinyca_client
    - docker
    - role: portainer
      vars:
        nfs_share_host: 192.168.10.58
        nfs_share_path: /mnt/store/dockerhost/portainer
        uid: 7000
        gid: 7000
