- name: Dockerhost Proxmox
  hosts: proxmox
  roles:
    - role: proxmox_base
      vms: "{{ groups['dockerhost'] | map('extract',hostvars) | list }}"
      when: dockerhost_full is defined
    - role: nfs_server
      vars:
        path: store/dockerhost
        sharenfs: "rw=@192.168.10.105,anongid=7000,anonuid=7000,all_squash"
        group:
          name: dockerhost
          gid: 7000
        user:
          name: dockerhost
          uid: 7000
      when: dockerhost_full is defined
    - role: nfs_server
      vars:
        path: store/media
        sharenfs: "rw=@192.168.10.0/24,anongid=6000,anonuid=6000,all_squash"
        group:
          name: shares
          gid: 6000
        user:
          name: shares
          uid: 6000
      when: dockerhost_full is defined
    - role: nfs_server
      vars:
        path: store/downloads
        sharenfs: "rw=@192.168.10.0/24,anongid=8000,anonuid=8000,all_squash"
        group:
          name: downloads
          gid: 8000
        user:
          name: downloads
          uid: 8000
      when: dockerhost_full is defined

- name: Dockerhost
  hosts: dockerhost
  roles:
    - basic_vm
    - tinyca_client
    - role: nfs_client
      vars:
        group:
          name: dockerhost
          gid: 7000
        src: 192.168.10.58:/mnt/store/dockerhost
        dest: /mnt/dockerhost
    - role: nfs_client
      vars:
        group:
          name: shares
          gid: 6000
        src: 192.168.10.58:/mnt/store/media
        dest: /mnt/media
    - role: nfs_client
      vars:
        group:
          name: downloads
          gid: 8000
        src: 192.168.10.58:/mnt/store/downloads
        dest: /mnt/downloads
    - role: docker
      vars:
        network_name: docker0
    - role: caddy
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: caddy
          uid: 10001
          gid: 7000
        data_dir: /mnt/dockerhost/caddy
    - role: portainer
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: portainer
          uid: 10002
          gid: 7000
        data_dir: /mnt/dockerhost/portainer
    - role: vault
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: vault
          uid: 10003
          gid: 7000
        data_dir: /mnt/dockerhost/vault
    - role: jellyfin
      vars:
        linux_group:
          name: shares
          gid: 6000
        linux_user:
          name: jellyfin
          uid: 10004
          gid: 6000
        data_dir: /mnt/dockerhost/jellyfin
        media_dir: /mnt/media
        network_name: docker0
    - role: uptime_kuma
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: uptime_kuma
          uid: 7000
          gid: 7000
        data_dir: /mnt/dockerhost/uptime_kuma
    - role: code-server
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: code_server
          uid: 10005
          gid: 7000
        data_dir: /mnt/dockerhost/code-server
    - role: home-assistant
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: home_assistant
          uid: 10006
          gid: 7000
        data_dir: /mnt/dockerhost/home-assistant
        network_name: docker0
    - role: prometheus
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: prometheus
          uid: 10007
          gid: 7000
        data_dir: /mnt/dockerhost/prometheus
    - role: qbittorrent
      vars:
        linux_group:
          name: dockerhost
          gid: 7000
        linux_user:
          name: qbittorrent
          uid: 10008
          gid: 7000
        config_dir: /mnt/dockerhost/qbittorrent
        downloads_dir: /mnt/downloads
    - role: docker_network
      vars:
        network_name: dockerhost
        connected:
          - caddy
          - portainer
          - vault
          - uptime-kuma
          - code-server
          - prometheus
          - qbittorrent
