- name: LDAP Proxmox
  hosts: proxmox
  roles:
    - role: proxmox_base
      vms: "{{ groups['ldap'] | map('extract',hostvars) | list }}"
      when: openldap_full is defined

- name: LDAP
  hosts: ldap
  roles:
    - basic_vm
    - tinyca_client
    - ldap
