- name: Shares Proxmox
  hosts: proxmox
  roles:
    - role: proxmox_base
      vms: "{{ groups['shares'] | map('extract',hostvars) | list }}"
      when: shares_full is defined
    - role: nfs_server
      vars:
        path: store/media
        sharenfs: "rw=@192.168.10.0/24,anongid=6000,anonuid=6000,all_squash"
        group:
          name: shares
          gid: 6000
        user:
          name: shares
          uid: 6000
      when: shares_full is defined

- name: Shares
  hosts: shares
  roles:
    - basic_vm
    - tinyca_client
    - role: nfs_client
      vars:
        group:
          name: shares
          gid: 6000
        src: 192.168.10.58:/mnt/store/media
        dest: /mnt/media
    - role: samba
      vars:
        netbios_name: SHARES
        shares:
          - name: media
            comment: Media Share
            path: /mnt/media
            group:
              name: shares
              gid: 6000
            user:
              name: shares
              uid: 6000
