- name: Time machine Proxmox
  hosts: proxmox
  roles:
    - role: proxmox_base
      vms: "{{ groups['time_machine'] | map('extract',hostvars) | list }}"
      when: time_machine_full is defined

- name: Time machine
  hosts: time_machine
  roles:
    - basic_vm
    - tinyca_client
    - role: nfs_client
      vars:
        src: 192.168.10.58:/mnt/store/time-machine
        dest: /mnt/time_machine
    - role: samba
      vars:
        share_root: /mnt/time_machine
        netbios_name: CAPSULE
    - nebula
