- name: TinyCA Proxmox
  hosts: proxmox
  roles:
    - role: proxmox_base
      vms: "{{ groups['tinyca'] | map('extract',hostvars) | list }}"
      when: tinyca_full is defined

- name: TinyCA
  hosts: tinyca
  roles:
    - basic_vm
    - docker
    - tinyca
