---
step_url: https://dl.step.sm/gh-release/cli/docs-ca-install/v0.21.0/step-cli_0.21.0_amd64.deb
tiny_ca_url: https://tinyca.local

openldap_org: noosxe
openldap_tld: com
openldap_domain_name: "{{ openldap_org + '.' + openldap_tld }}"
ldap_hostname: "{{ 'ldap.' + openldap_domain_name }}"

# The database engine (mdb / hdb)
openldap_db_engine: MDB
