---
- name: Install packages
  ansible.builtin.import_tasks: pkgs.yaml

- name: Create a volume
  become: true
  community.docker.docker_volume:
    name: portainer_data

- name: Create a data container'
  become: true
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    restart_policy: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
