---
- name: Download nebula binaries
  unarchive:
    src: "{{ nebula_url }}"
    dest: /usr/local/bin
    remote_src: yes

- name: Create config directory
  file:
    path: /etc/nebula
    state: directory

- name: Copy the systemd service file
  template:
    src: nebula.service.j2
    dest: /etc/systemd/system/nebula.service
  notify: Restart the nebula service

- name: Copy config file
  template:
    src: config.yaml.j2
    dest: /etc/nebula/config.yaml
  notify: Restart the nebula service

- name: Allow access to udp port {{ nebula_port }}
  ufw:
    rule: allow
    port: "{{ nebula_port }}"
    proto: udp
