---
- name: Install packages
  ansible.builtin.import_tasks: pkgs.yaml

- name: Ensure the group exists
  become: true
  ansible.builtin.group:
    name: "{{ linux_group.name }}"
    state: present
    gid: "{{ linux_group.gid }}"

- name: Ensure the user exists
  become: true
  ansible.builtin.user:
    name: "{{ linux_user.name }}"
    uid: "{{ linux_user.uid }}"
    group: "{{ linux_group.name }}"

- name: Ensure the prometheus dir exists
  become: true
  become_user: "{{ linux_user.name }}"
  ansible.builtin.file:
    path: "{{ data_dir }}"
    state: directory
    mode: "0770"

- name: Ensure the prometheus config dir exists
  become: true
  become_user: "{{ linux_user.name }}"
  ansible.builtin.file:
    path: "{{ data_dir }}/config"
    state: directory
    mode: "0770"

- name: Ensure the prometheus data dir exists
  become: true
  become_user: "{{ linux_user.name }}"
  ansible.builtin.file:
    path: "{{ data_dir }}/data"
    state: directory
    mode: "0770"

- name: Create the container
  become: true
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:v2.40.1
    restart_policy: always
    volumes:
      - "{{ data_dir }}/config:/etc/prometheus"
      - "{{ data_dir }}/data:/prometheus"
