---
- name: Remove all but selected list of containers
  become: true
  community.docker.docker_network:
    name: "{{ network_name }}"
    connected: "{{ connected }}"
    driver_options:
      com.docker.network.bridge.name: "{{ network_name }}"
