---
- name: Install ubuntu acl package
  become: true
  ansible.builtin.apt:
    name: acl

- name: Install Samba packages
  become: true
  ansible.builtin.apt:
    name:
      - samba
      - samba-common
      - avahi-daemon
