---
- name: Ensure groups exist
  become: true
  ansible.builtin.group:
    name: "{{ item.group.name }}"
    gid: "{{ item.group.gid }}"
    state: present
  loop: "{{ shares }}"

- name: Ensure users exist
  become: true
  ansible.builtin.user:
    name: "{{ item.user.name }}"
    group: "{{ item.group.name }}"
    shell: /bin/bash
    create_home: false
    system: false
    uid: "{{ item.user.uid }}"
  loop: "{{ shares }}"

- name: Install smb.conf
  become: true
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: Restart smbd service

- name: Install samba.service
  become: true
  ansible.builtin.template:
    src: samba.service.j2
    dest: /etc/avahi/services/samba.service
  notify: Restart avahi-daemon service

# - name: Allow samba from mesh
#   become: true
#   community.general.ufw:
#     rule: allow
#     port: "{{ smb_ports }}"
#     src: 192.168.150.0/24

# - name: Allow avahi-daemon from mesh
#   become: true
#   community.general.ufw:
#     rule: allow
#     port: 5353
#     proto: udp
#     src: 192.168.150.0/24

- name: Allow samba locally
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ smb_ports }}"
    src: 192.168.10.0/24

- name: Allow avahi-daemon locally
  become: true
  community.general.ufw:
    rule: allow
    port: 5353
    proto: udp
    src: 192.168.10.0/24
