---
- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip

- name: Install yubikey-manager
  become: true
  ansible.builtin.pip:
    name: yubikey-manager==4.0.9

- name: Install step-ca
  become: true
  ansible.builtin.apt:
    deb: "{{ step_ca_url }}"

- name: Install step-cli
  become: true
  ansible.builtin.apt:
    deb: "{{ step_url }}"
