---
- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip

- name: Add the kubic repo key
  become: true
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key
    state: present

- name: Add the kubic repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
    filename: devel:kubic:libcontainers:stable.list
    state: present

- name: Install podman
  become: true
  ansible.builtin.apt:
    name: podman

- name: Install step-cli
  become: true
  ansible.builtin.apt:
    deb: "{{ step_url }}"
