---
- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip

- name: Install libpcsclite-dev
  become: true
  ansible.builtin.apt:
    name: libpcsclite-dev

- name: Install pcscd
  become: true
  ansible.builtin.apt:
    name: pcscd

- name: Enable pcscd service
  become: true
  service:
    name: pcscd
    enabled: yes
    state: started

- name: Install swig
  become: true
  ansible.builtin.pip:
    name: swig

- name: Install yubikey-manager
  become: true
  ansible.builtin.pip:
    name: yubikey-manager==4.0.9

- name: Add the kubic repo key
  become: true
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key
    state: present

- name: Add the kubic repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
    filename: devel:kubic:libcontainers:stable.list
    state: present

- name: Install podman
  become: true
  ansible.builtin.apt:
    name: podman

- name: Install step-cli
  become: true
  ansible.builtin.apt:
    deb: "{{ step_url }}"
