---
- name: Install ubuntu acl package
  become: true
  apt:
    name: acl

- name: Install pip
  become: true
  apt:
    name: python3-pip

- name: Install step-cli
  become: true
  apt:
    deb: "{{ step_url }}"
