---
- name: Check for {{ ca_json }}
  become: true
  become_user: "{{ ca_user }}"
  ansible.builtin.stat:
    path: "{{ ca_json }}"
  register: ca_json_result

- name: ca.json already exists
  ansible.builtin.debug:
    msg: "Config already exists!"
  when: ca_json_result.stat.exists

- name: Init step ca
  become: true
  become_user: "{{ ca_user }}"
  ansible.builtin.command:
    cmd: step ca init --name {{ ca_name }} --dns {{ ca_dns }} --address localhost:443 --provisioner "{{ ca_provisioner }}" --password-file "{{ ca_dir }}/{{ password_file }}"
    creates: "{{ ca_json }}"
  environment:
    STEPPATH: "{{ ca_dir }}"
  register: stepca_output
  when: not ca_json_result.stat.exists

- name: Display step ca init output
  debug:
    msg: "{{ item }}"
    verbosity: 2
  with_items:
    - "{{ stepca_output.stdout_lines }}"
    - "{{ stepca_output.stderr_lines }}"
  when: stepca_output.stdout_lines is defined and stepca_output.stderr_lines is defined

- name: Add ACME provisioner
  become: true
  become_user: "{{ ca_user }}"
  ansible.builtin.command:
    cmd: step ca provisioner add acme --type acme --ca-config {{ ca_json }}
  environment:
    STEPPATH: "{{ ca_dir }}"
  when: not ca_json_result.stat.exists

- name: Move cert files
  become: true
  become_user: "{{ ca_user }}"
  command: "mv {{ item.src }} {{ item.dest }}"
  loop:
    - {
        src: "{{ ca_tmp_dir }}/intermediate_ca.crt",
        dest: "{{ ca_dir }}/certs/intermediate_ca.crt",
      }
    - {
        src: "{{ ca_tmp_dir }}/root_ca.crt",
        dest: "{{ ca_dir }}/certs/root_ca.crt",
      }
  notify: Start step CA

- name: Delete step-ca secrets
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ca_dir }}/secrets/intermediate_ca_key"
    - "{{ ca_dir }}/secrets/root_ca_key"
  notify: Start step CA

- name: Setup step-ca config
  become: true
  become_user: "{{ ca_user }}"
  replace:
    path: "{{ ca_json }}"
    regexp: '^\s*("key":\s*"\/etc\/step-ca\/secrets\/intermediate_ca_key",)\s*$'
    replace: |
      "key": "yubikey:slot-id=9c",
      "kms": {
        "type": "yubikey",
        "pin": "123456"
      },
  notify: Start step CA
