---
- name: Install yubikey-manager
  become: true
  ansible.builtin.apt:
    name: yubikey-manager

- name: Install step-ca
  become: true
  ansible.builtin.apt:
    deb: "{{ step_ca_url }}"

- name: Install step-cli
  become: true
  ansible.builtin.apt:
    deb: "{{ step_url }}"

- name: Create the step-ca dir
  become: true
  ansible.builtin.file:
    path: "{{ ca_dir }}"
    state: directory
    mode: "0755"

- name: Add the step-ca user
  become: true
  ansible.builtin.user:
    name: "{{ ca_user }}"
    home: "{{ ca_dir }}"
    shell: /bin/false
    system: true

- name: Set CAP_NET_BIND_SERVICE=+eip on step-ca
  become: true
  community.general.capabilities:
    path: "{{ step_ca_bin }}"
    capability: CAP_NET_BIND_SERVICE=+ep
    state: present

- name: Copy the password file
  become: true
  ansible.builtin.copy:
    src: "./files/password.txt"
    dest: "{{ ca_dir }}/{{ password_file }}"
    mode: "0700"

- name: Recursively change ownership of the step-ca dir
  become: true
  ansible.builtin.file:
    path: "{{ ca_dir }}"
    state: directory
    recurse: yes
    owner: "{{ ca_user }}"
    group: "{{ ca_user }}"

- name: Check for {{ ca_json }}
  become: true
  become_user: "{{ ca_user }}"
  ansible.builtin.stat:
    path: "{{ ca_json }}"
  register: ca_json_result

- name: ca.json already exists
  ansible.builtin.debug:
    msg: "This will fail when config already exists."
  failed_when: ca_json_result.stat.exists

- name: Init step ca
  become: true
  become_user: "{{ ca_user }}"
  ansible.builtin.command:
    cmd: step ca init --name {{ ca_name }} --dns {{ ca_dns }} --address {{ ansible_host }}:443 --provisioner "{{ ca_provisioner }}" --password-file "{{ ca_dir }}/{{ password_file }}"
    creates: "{{ ca_json }}"
  environment:
    STEPPATH: "{{ ca_dir }}"
  register: stepca_output
  notify: Start step CA

- name: Display step ca init output
  debug:
    msg: "{{ item }}"
    verbosity: 2
  with_items:
    - "{{ stepca_output.stdout_lines }}"
    - "{{ stepca_output.stderr_lines }}"
  when: stepca_output.stdout_lines is defined and stepca_output.stderr_lines is defined

- name: Copy systemd unit
  become: true
  template:
    src: step-ca.service.j2
    dest: /etc/systemd/system/step-ca.service
  notify: Start step CA
