---
- name: Include secrets
  include_vars: ../../../secrets.yaml

- name: Install apt packages
  import_tasks: apt.yaml

- name: Install udev rules
  import_tasks: udev.yaml

- name: Setup systemd step-ca unit
  import_tasks: systemd.yaml

- name: Setup step-ca service environment
  import_tasks: service_env.yaml

- name: Setup CA certs and keys
  import_tasks: keys_certs.yaml

- name: Initialize CA config
  import_tasks: ca_config.yaml

- name: Setup firewall
  import_tasks: firewall.yaml
