---
- name: Include secrets
  ansible.builtin.include_vars: ../../../secrets.yaml

- name: Install apt packages
  ansible.builtin.import_tasks: apt.yaml

- name: Install udev rules
  ansible.builtin.import_tasks: udev.yaml

- name: Setup step-ca service environment
  ansible.builtin.import_tasks: service_env.yaml

- name: Setup systemd step-ca unit
  ansible.builtin.import_tasks: systemd.yaml

- name: Setup CA certs and keys
  ansible.builtin.import_tasks: keys_certs.yaml

- name: Initialize CA config
  ansible.builtin.import_tasks: ca_config.yaml

- name: Setup firewall
  ansible.builtin.import_tasks: firewall.yaml
