---
- name: Create the step-ca dir
  become: true
  ansible.builtin.file:
    path: "{{ ca_dir }}"
    state: directory
    mode: "0755"

- name: Create the step-ca/usb dir
  become: true
  ansible.builtin.file:
    path: "{{ ca_dir }}/usb"
    state: directory
    mode: "0700"

- name: Add the step-ca user
  become: true
  ansible.builtin.user:
    name: "{{ ca_user }}"
    groups:
      - docker
    home: "{{ ca_dir }}"
    shell: /bin/bash
    uid: "{{ ca_uid }}"
    system: false

- name: Get user infos
  ansible.builtin.getent:
    database: passwd

- name: Change ownership of the step-ca dir
  become: true
  ansible.builtin.file:
    path: "{{ ca_dir }}"
    state: directory
    recurse: true
    owner: "{{ ca_user }}"
    group: "{{ ca_user }}"

- name: Copy the password file
  become: true
  ansible.builtin.template:
    src: "password.txt.j2"
    dest: "{{ ca_dir }}/{{ password_file }}"
    mode: "0700"
    owner: "{{ ca_user }}"
    group: "{{ ca_user }}"
