---
- name: Create dev-yubikey.device.wants directory
  become: true
  file:
    path: /etc/systemd/system/dev-yubikey.device.wants
    state: directory
    mode: "0755"

- name: Copy systemd unit
  become: true
  template:
    src: step-ca.service.j2
    dest: /etc/systemd/system/step-ca.service
  notify: Start step CA

- name: Create symbolic link
  become: true
  file:
    src: /etc/systemd/system/step-ca.service
    dest: /etc/systemd/system/dev-yubikey.device.wants/step-ca.service
    state: link
  notify: Start step CA
