---
- name: Copy yubikey udev rules
  become: true
  template:
    src: 75-yubikey.rules.j2
    dest: /etc/udev/rules.d/75-yubikey.rules
  notify: Reload udevadm

- name: Copy flashdrive udev rules
  become: true
  template:
    src: 76-flashdrive.rules.j2
    dest: /etc/udev/rules.d/76-flashdrive.rules
  notify: Reload udevadm

- name: Trigger udevadm add action
  become: true
  shell: udevadm trigger --action=add

- name: Wait for /dev/flashdrive
  wait_for:
    path: /dev/flashdrive
