name: Publish step-ca docker image

on: [push]

jobs:
  push_to_ghcrio:
    name: Build and publish step-ca docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./docker/step-ca
          build-args: |
            SMALLSTEP_CLI_VERSION=0.21.0
            SMALLSTEP_CA_VERSION=0.21.0
          cache-from: |
            type=gha
          cache-to: |
            type=gha
          push: true
          tags: ghcr.io/noosxe/homelab/step-ca-debian:latest
